//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cagrilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cagrilar()
        {
            this.cagridetaylar = new HashSet<cagridetaylar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> cagrifirma { get; set; }
        public string konu { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> cagripersonel { get; set; }
    
        public virtual firmalar firmalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cagridetaylar> cagridetaylar { get; set; }
        public virtual personel personel { get; set; }
    }
}
