//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gorevler()
        {
            this.gorevdetay = new HashSet<gorevdetay>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GorevVeren { get; set; }
        public Nullable<int> GorevAlan { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorevdetay> gorevdetay { get; set; }
        public virtual personel personel { get; set; }
        public virtual personel personel1 { get; set; }
    }
}
