//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class istakipEntities1 : DbContext
    {
        public istakipEntities1()
            : base("name=istakipEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<departmanlar> departmanlar { get; set; }
        public virtual DbSet<firmalar> firmalar { get; set; }
        public virtual DbSet<gorevdetay> gorevdetay { get; set; }
        public virtual DbSet<gorevler> gorevler { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<cagrilar> cagrilar { get; set; }
        public virtual DbSet<cagridetaylar> cagridetaylar { get; set; }
    }
}
